/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestSharedRouteImport } from './routes/test-shared'
import { Route as TestRscRouteImport } from './routes/test-rsc'
import { Route as RscDemoRouteImport } from './routes/rsc-demo'
import { Route as IndexRouteImport } from './routes/index'

const TestSharedRoute = TestSharedRouteImport.update({
  id: '/test-shared',
  path: '/test-shared',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRscRoute = TestRscRouteImport.update({
  id: '/test-rsc',
  path: '/test-rsc',
  getParentRoute: () => rootRouteImport,
} as any)
const RscDemoRoute = RscDemoRouteImport.update({
  id: '/rsc-demo',
  path: '/rsc-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rsc-demo': typeof RscDemoRoute
  '/test-rsc': typeof TestRscRoute
  '/test-shared': typeof TestSharedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rsc-demo': typeof RscDemoRoute
  '/test-rsc': typeof TestRscRoute
  '/test-shared': typeof TestSharedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rsc-demo': typeof RscDemoRoute
  '/test-rsc': typeof TestRscRoute
  '/test-shared': typeof TestSharedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rsc-demo' | '/test-rsc' | '/test-shared'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rsc-demo' | '/test-rsc' | '/test-shared'
  id: '__root__' | '/' | '/rsc-demo' | '/test-rsc' | '/test-shared'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RscDemoRoute: typeof RscDemoRoute
  TestRscRoute: typeof TestRscRoute
  TestSharedRoute: typeof TestSharedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-shared': {
      id: '/test-shared'
      path: '/test-shared'
      fullPath: '/test-shared'
      preLoaderRoute: typeof TestSharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-rsc': {
      id: '/test-rsc'
      path: '/test-rsc'
      fullPath: '/test-rsc'
      preLoaderRoute: typeof TestRscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsc-demo': {
      id: '/rsc-demo'
      path: '/rsc-demo'
      fullPath: '/rsc-demo'
      preLoaderRoute: typeof RscDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RscDemoRoute: RscDemoRoute,
  TestRscRoute: TestRscRoute,
  TestSharedRoute: TestSharedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
