import { createFromFetch, createFromReadableStream } from '@vitejs/plugin-rsc/browser';

export type RscPayload = {
  content: React.ReactNode;
};

const RSC_SERVER_URL = import.meta.env.VITE_RSC_SERVER_URL || 'http://localhost:4000';

// Note: @vitejs/plugin-rsc/browser automatically initializes setRequireModule
// using virtual:vite-rsc/client-references generated by the RSC plugin.
// The plugin scans client components and generates the ID -> import mapping.
// No manual setup needed - just ensure the RSC plugin is configured correctly!

// Step 1: Fetch raw RSC payload from server (for inspection only)
export async function fetchRawRscPayload(markdown: string): Promise<Response> {
  const response = await fetch(`${RSC_SERVER_URL}/render`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'text/x-component',
    },
    body: JSON.stringify({ markdown }),
  });
  
  if (!response.ok) {
    throw new Error(`RSC fetch failed: ${response.statusText}`);
  }
  
  return response;
}

// Step 2: Parse RSC payload using @vitejs/plugin-rsc/browser
// This properly deserializes the RSC stream into React elements
// Returns Promise<RscPayload> which can be used with React's use() hook
export function parseRscPayload(markdown: string): Promise<RscPayload> {
  const responsePromise = fetch(`${RSC_SERVER_URL}/render`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'text/x-component',
    },
    body: JSON.stringify({ markdown }),
  });
  
  // createFromFetch handles the RSC payload deserialization
  // It returns Promise<RscPayload> which resolves to the parsed React elements
  return createFromFetch<RscPayload>(responsePromise);
}

// Alternative: Parse from a ReadableStream (useful for cached payloads)
export function parseRscFromStream(stream: ReadableStream<Uint8Array>): Promise<RscPayload> {
  return createFromReadableStream<RscPayload>(stream);
}

